apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rag-openshift-ai-api.fullname" . }}
  labels:
    {{- include "rag-openshift-ai-api.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  
  selector:
    matchLabels:
      {{- include "rag-openshift-ai-api.selectorLabels" . | nindent 6 }}
  
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  
  template:
    metadata:
      labels:
        {{- include "rag-openshift-ai-api.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podTemplateAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "rag-openshift-ai-api.serviceAccountName" . }}
      {{- end }}
      
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      
      {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- if .Values.initContainers }}
      initContainers:
        {{- range .Values.initContainers }}
        - name: {{ .name }}
          image: {{ .image }}
          {{- if .command }}
          command:
            {{- toYaml .command | nindent 12 }}
          {{- end }}
          {{- if .args }}
          args:
            {{- toYaml .args | nindent 12 }}
          {{- end }}
          {{- if .env }}
          env:
            {{- toYaml .env | nindent 12 }}
          {{- end }}
          {{- if .volumeMounts }}
          volumeMounts:
            {{- toYaml .volumeMounts | nindent 12 }}
          {{- end }}
          {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
      
      {{- if .Values.volumes }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}
      
      {{- if .Values.configMaps.appConfig.enabled }}
      volumes:
        - name: app-config
          configMap:
            name: {{ include "rag-openshift-ai-api.fullname" . }}-config
      {{- end }}
      
      {{- if .Values.secrets.elasticsearch.enabled }}
      volumes:
        - name: elasticsearch-secrets
          secret:
            secretName: {{ .Values.secrets.elasticsearch.secretName }}
      {{- end }}
      
      {{- if .Values.secrets.vllm.enabled }}
      volumes:
        - name: vllm-secrets
          secret:
            secretName: {{ .Values.secrets.vllm.secretName }}
      {{- end }}
      
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        
        {{- if .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        {{- end }}
        
        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- end }}
        
        {{- if .Values.startupProbe }}
        startupProbe:
          {{- toYaml .Values.startupProbe | nindent 10 }}
        {{- end }}
        
        {{- if .Values.lifecycle }}
        lifecycle:
          {{- toYaml .Values.lifecycle | nindent 10 }}
        {{- end }}
        
        env:
        # API Configuration
        - name: API_LOG_LEVEL
          value: {{ .Values.config.api.logLevel | quote }}
        - name: API_DEBUG
          value: {{ .Values.config.api.debug | quote }}
        - name: API_CORS_ORIGINS
          value: {{ .Values.config.api.corsOrigins | join "," | quote }}
        - name: API_MAX_REQUEST_SIZE
          value: {{ .Values.config.api.maxRequestSize | quote }}
        - name: API_REQUEST_TIMEOUT
          value: {{ .Values.config.api.requestTimeout | quote }}
        - name: API_RATE_LIMIT_ENABLED
          value: {{ .Values.config.api.rateLimit.enabled | quote }}
        - name: API_RATE_LIMIT_REQUESTS_PER_MINUTE
          value: {{ .Values.config.api.rateLimit.requestsPerMinute | quote }}
        - name: API_RATE_LIMIT_BURST_SIZE
          value: {{ .Values.config.api.rateLimit.burstSize | quote }}
        
        # Elasticsearch Configuration
        - name: ELASTICSEARCH_URL
          value: {{ .Values.config.elasticsearch.url | quote }}
        - name: ELASTICSEARCH_INDEX
          value: {{ .Values.config.elasticsearch.index | quote }}
        - name: ELASTICSEARCH_SSL_VERIFY
          value: {{ .Values.config.elasticsearch.sslVerify | quote }}
        - name: ELASTICSEARCH_TIMEOUT
          value: {{ .Values.config.elasticsearch.timeout | quote }}
        - name: ELASTICSEARCH_MAX_RETRIES
          value: {{ .Values.config.elasticsearch.maxRetries | quote }}
        - name: ELASTICSEARCH_MAX_CONNECTIONS
          value: {{ .Values.config.elasticsearch.maxConnections | quote }}
        - name: ELASTICSEARCH_RETRY_ON_TIMEOUT
          value: {{ .Values.config.elasticsearch.retryOnTimeout | quote }}
        
        {{- if .Values.secrets.elasticsearch.enabled }}
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.elasticsearch.secretName }}
              key: {{ .Values.secrets.elasticsearch.usernameKey | default "username" }}
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.elasticsearch.secretName }}
              key: {{ .Values.secrets.elasticsearch.passwordKey | default "password" }}
        {{- else }}
        - name: ELASTICSEARCH_USERNAME
          value: {{ .Values.config.elasticsearch.username | quote }}
        - name: ELASTICSEARCH_PASSWORD
          value: {{ .Values.config.elasticsearch.password | quote }}
        {{- end }}
        
        # vLLM Configuration
        - name: VLLM_ENDPOINT
          value: {{ .Values.config.vllm.endpoint | quote }}
        - name: VLLM_DEFAULT_MODEL
          value: {{ .Values.config.vllm.defaultModel | quote }}
        - name: VLLM_MAX_TOKENS
          value: {{ .Values.config.vllm.maxTokens | quote }}
        - name: VLLM_TEMPERATURE
          value: {{ .Values.config.vllm.temperature | quote }}
        - name: VLLM_TOP_P
          value: {{ .Values.config.vllm.topP | quote }}
        - name: VLLM_TIMEOUT
          value: {{ .Values.config.vllm.timeout | quote }}
        
        {{- if .Values.secrets.vllm.enabled }}
        - name: VLLM_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.vllm.secretName }}
              key: {{ .Values.secrets.vllm.apiKeyKey | default "api-key" }}
        {{- end }}
        
        # RAG Configuration
        - name: RAG_TOP_K
          value: {{ .Values.config.rag.retrieval.topK | quote }}
        - name: RAG_SIMILARITY_THRESHOLD
          value: {{ .Values.config.rag.retrieval.similarityThreshold | quote }}
        - name: RAG_MAX_TOKENS
          value: {{ .Values.config.rag.retrieval.maxTokens | quote }}
        - name: RAG_SEARCH_TYPE
          value: {{ .Values.config.rag.retrieval.searchType | quote }}
        - name: RAG_GENERATION_MAX_TOKENS
          value: {{ .Values.config.rag.generation.maxTokens | quote }}
        - name: RAG_GENERATION_TEMPERATURE
          value: {{ .Values.config.rag.generation.temperature | quote }}
        - name: RAG_GENERATION_TOP_P
          value: {{ .Values.config.rag.generation.topP | quote }}
        - name: RAG_GENERATION_TOP_K
          value: {{ .Values.config.rag.generation.topK | quote }}
        - name: RAG_GENERATION_REPETITION_PENALTY
          value: {{ .Values.config.rag.generation.repetitionPenalty | quote }}
        - name: RAG_CACHE_ENABLED
          value: {{ .Values.config.rag.cache.enabled | quote }}
        - name: RAG_CACHE_TTL
          value: {{ .Values.config.rag.cache.ttl | quote }}
        - name: RAG_CACHE_MAX_SIZE
          value: {{ .Values.config.rag.cache.maxSize | quote }}
        
        # Logging Configuration
        - name: LOG_LEVEL
          value: {{ .Values.logging.level | quote }}
        - name: LOG_FORMAT
          value: {{ .Values.logging.format | quote }}
        - name: LOG_OUTPUT
          value: {{ .Values.logging.output | quote }}
        
        # Monitoring Configuration
        - name: METRICS_ENABLED
          value: {{ .Values.monitoring.enabled | quote }}
        
        # Pod Information
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        
        # Service Information
        - name: SERVICE_NAME
          value: {{ include "rag-openshift-ai-api.fullname" . }}
        
        {{- if .Values.env }}
        {{- toYaml .Values.env | nindent 8 }}
        {{- end }}
        
        {{- if .Values.volumeMounts }}
        volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 10 }}
        {{- end }}
        
        {{- if .Values.configMaps.appConfig.enabled }}
        volumeMounts:
          - name: app-config
            mountPath: /app/config
            readOnly: true
        {{- end }}
        
        {{- if .Values.secrets.elasticsearch.enabled }}
        volumeMounts:
          - name: elasticsearch-secrets
            mountPath: /app/secrets/elasticsearch
            readOnly: true
        {{- end }}
        
        {{- if .Values.secrets.vllm.enabled }}
        volumeMounts:
          - name: vllm-secrets
            mountPath: /app/secrets/vllm
            readOnly: true
        {{- end }}
        
        {{- if .Values.logging.fluentd.enabled }}
        volumeMounts:
          - name: varlog
            mountPath: /var/log
        {{- end }}
      
      {{- if .Values.sidecarContainers }}
      containers:
        {{- range .Values.sidecarContainers }}
        - name: {{ .name }}
          image: {{ .image }}
          {{- if .ports }}
          ports:
            {{- toYaml .ports | nindent 12 }}
          {{- end }}
          {{- if .env }}
          env:
            {{- toYaml .env | nindent 12 }}
          {{- end }}
          {{- if .volumeMounts }}
          volumeMounts:
            {{- toYaml .volumeMounts | nindent 12 }}
          {{- end }}
          {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
      
      {{- if .Values.logging.fluentd.enabled }}
      volumes:
        - name: varlog
          emptyDir: {}
      {{- end }} 