{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "rag-openshift-ai-api.fullname" . }}
  labels:
    {{- include "rag-openshift-ai-api.labels" . | nindent 4 }}
spec:
  {{- if .Values.route.hostname }}
  host: {{ .Values.route.hostname }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "rag-openshift-ai-api.fullname" . }}
    weight: 100
  port:
    targetPort: {{ .Values.service.targetPort }}
{{- end }} 