apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rag-openshift-ai-api.fullname" . }}-secrets
  labels:
    {{- include "rag-openshift-ai-api.labels" . | nindent 4 }}
type: Opaque
data:
  # Elasticsearch credentials
  es-username: {{ .Values.elasticsearch.username | b64enc | quote }}
  es-password: {{ .Values.elasticsearch.password | b64enc | quote }}
  
  # Application security
  secret-key: {{ .Values.secretKey | b64enc | quote }} 