apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rag-api.fullname" . }}-secrets
  labels:
    {{- include "rag-api.labels" . | nindent 4 }}
type: Opaque
data:
  # Elasticsearch credentials
  ES_USERNAME: {{ .Values.elasticsearch.username | b64enc | quote }}
  ES_PASSWORD: {{ .Values.elasticsearch.password | b64enc | quote }}
  
  # Application security
  ENV_SECRET_KEY: {{ .Values.environment.secretKey | b64enc | quote }} 