{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rag-openshift-ai-api.fullname" . }}
  labels:
    {{- include "rag-openshift-ai-api.labels" . | nindent 4 }}
    release: prometheus
spec:
  selector:
    matchLabels:
      {{- include "rag-openshift-ai-api.selectorLabels" . | nindent 6 }}
  
  endpoints:
    - port: http
      path: /api/v1/metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval | default "30s" }}
      scrapeTimeout: 10s
      honorLabels: true
{{- end }} 